# Site settings
title: "Code & Surf Camp - Le Wagon"
email: contact@lewagon.org
description: "Apportez votre planche et votre ordi pour 2 semaines de formation Code & Surf dans les Landes !"
baseurl: "/surfcamp"

# Build settings
markdown: kramdown
permalink: pretty
